name: Node.js

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  node:
    strategy:
      matrix:
        node-version: [14, 16, 18, latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - if: matrix.node-version == 14
        run: npm install --global npm@7
      - run: npm ci
      - run: npm test
      - run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint
      - run: npx prettier --check .
